language: python
python:
  - '3.4'
  - '3.3'
  - '3.2'
  - '2.7'
install:
  - pip install -r requirements.txt
  - python setup.py develop
script:
  - test -z "$STORMPATH_API_KEY_SECRET" || python setup.py test
  - cd docs && make html
env:
  global:
  - secure: hAO+zuFzu6JSBMbZv6I0lMxRiD1NPxIFoKTFzWZ6R9v7CMzt6Gyisp9u8TVdLMyluGgcu1OMXfauOy57q2N85aQBPosgyrDb9PW4NI9bpEOP3B2sjGMfpYLK94RylfjbiginkuhQElgqOJ0V0gGiJ1+pQ53AdY0TB5EMmI4YmSs=
  - secure: c7r7HLIBk+jbfrJtJCDbVW4n6izcPx69pn32HltNYV+bd6YZIpIFvR4D7dsvS3dO18ITel2oqATuaxdG0U1UAEssyDiwoCcUPN8R822i5pGAgXV/CLVbxPRNUkVGRJslDzNvjYqSXVULaCl1g5yMHcdlaylBGAKwhXCF8xCAFcY=
